#!/usr/bin/env python3
"""Train a small U-Net to segment removable paper crease/wrinkle defects.

This is a research-side prototype. It trains from the paired synthetic dataset
generated by generate_synthetic_crease_dataset.py and writes:

- model.pt: PyTorch checkpoint
- metrics.json: train/validation loss history
- validation-contact-sheet.jpg: visual sanity check

The model input is derived only from the degraded image, so the trained model can
be used on real scans. Clean targets and masks are used only for supervision.

Usage:
    .venv/bin/python scripts/train_crease_mask_model.py \
      --dataset tmp/synthetic-crease-dataset \
      --epochs 8
"""

from __future__ import annotations

import argparse
import json
import math
import random
from dataclasses import dataclass
from pathlib import Path

import cv2
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train crease/wrinkle mask model.")
    parser.add_argument("--dataset", default="tmp/synthetic-crease-dataset", help="Synthetic dataset directory.")
    parser.add_argument("--out-dir", default="tmp/crease-mask-model", help="Output directory.")
    parser.add_argument("--epochs", type=int, default=10, help="Training epochs.")
    parser.add_argument("--batch-size", type=int, default=4, help="Batch size.")
    parser.add_argument("--crop-size", type=int, default=320, help="Square random crop size.")
    parser.add_argument("--base-channels", type=int, default=16, help="Base U-Net channel count.")
    parser.add_argument("--learning-rate", type=float, default=2e-3, help="AdamW learning rate.")
    parser.add_argument("--seed", type=int, default=20260518, help="Random seed.")
    parser.add_argument("--val-ratio", type=float, default=0.20, help="Validation split ratio.")
    parser.add_argument("--num-workers", type=int, default=0, help="DataLoader workers.")
    return parser.parse_args()


def set_seeds(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)


def select_device() -> torch.device:
    if torch.backends.mps.is_available():
        return torch.device("mps")
    if torch.cuda.is_available():
        return torch.device("cuda")
    return torch.device("cpu")


def read_gray(path: Path) -> np.ndarray:
    image = cv2.imread(str(path), cv2.IMREAD_GRAYSCALE)
    if image is None:
        raise RuntimeError(f"Failed to read image: {path}")
    return image


def read_bgr(path: Path) -> np.ndarray:
    image = cv2.imread(str(path), cv2.IMREAD_COLOR)
    if image is None:
        raise RuntimeError(f"Failed to read image: {path}")
    return image


def write_image(path: Path, image: np.ndarray) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not cv2.imwrite(str(path), image):
        raise RuntimeError(f"Failed to write image: {path}")


def load_manifest(dataset_dir: Path) -> list[dict]:
    manifest_path = dataset_dir / "manifest.jsonl"
    rows = []
    with manifest_path.open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    if not rows:
        raise RuntimeError(f"No rows in {manifest_path}")
    return rows


def build_input_channels(gray: np.ndarray, expected_channels: int = 5) -> np.ndarray:
    source = gray.astype(np.float32) / 255.0
    local_mean = cv2.GaussianBlur(source, (0, 0), sigmaX=18.0, sigmaY=18.0)
    broad_mean = cv2.GaussianBlur(source, (0, 0), sigmaX=52.0, sigmaY=52.0)
    local_dark_delta = np.clip(local_mean - source, -0.5, 0.5) + 0.5
    local_bright_delta = np.clip(source - local_mean, -0.5, 0.5) + 0.5
    broad_dark_delta = np.clip(broad_mean - source, -0.5, 0.5) + 0.5

    grad_x = cv2.Sobel(source, cv2.CV_32F, 1, 0, ksize=3)
    grad_y = cv2.Sobel(source, cv2.CV_32F, 0, 1, ksize=3)
    gradient = np.sqrt(grad_x * grad_x + grad_y * grad_y)
    gradient = np.clip(gradient * 5.0, 0.0, 1.0)

    if expected_channels == 3:
        return np.stack([source, local_dark_delta, gradient], axis=0).astype(np.float32)
    return np.stack(
        [source, local_dark_delta, local_bright_delta, broad_dark_delta, gradient],
        axis=0,
    ).astype(np.float32)


@dataclass(frozen=True)
class Crop:
    top: int
    left: int
    size: int


class CreaseDataset(Dataset):
    def __init__(
        self,
        dataset_dir: Path,
        rows: list[dict],
        crop_size: int,
        train: bool,
        seed: int,
    ) -> None:
        self.dataset_dir = dataset_dir
        self.rows = rows
        self.crop_size = crop_size
        self.train = train
        self.rng = random.Random(seed)

    def __len__(self) -> int:
        return len(self.rows)

    def _make_crop(self, height: int, width: int, target: np.ndarray, foreground: np.ndarray) -> Crop:
        size = min(self.crop_size, height, width)
        if not self.train:
            return Crop((height - size) // 2, (width - size) // 2, size)

        positive = np.argwhere(target > 0)
        if len(positive) and self.rng.random() < 0.74:
            y, x = positive[self.rng.randrange(len(positive))]
            top = int(np.clip(y - self.rng.randint(size // 4, size * 3 // 4), 0, height - size))
            left = int(np.clip(x - self.rng.randint(size // 4, size * 3 // 4), 0, width - size))
        elif not len(positive) and self.rng.random() < 0.64 and np.any(foreground > 0):
            foreground_pixels = np.argwhere(foreground > 0)
            y, x = foreground_pixels[self.rng.randrange(len(foreground_pixels))]
            top = int(np.clip(y - self.rng.randint(size // 4, size * 3 // 4), 0, height - size))
            left = int(np.clip(x - self.rng.randint(size // 4, size * 3 // 4), 0, width - size))
        else:
            top = self.rng.randint(0, height - size)
            left = self.rng.randint(0, width - size)
        return Crop(top, left, size)

    def _augment(self, inputs: np.ndarray, target: np.ndarray, foreground: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        if not self.train:
            return inputs, target, foreground

        if self.rng.random() < 0.5:
            inputs = inputs[:, :, ::-1].copy()
            target = target[:, ::-1].copy()
            foreground = foreground[:, ::-1].copy()
        if self.rng.random() < 0.5:
            inputs = inputs[:, ::-1, :].copy()
            target = target[::-1, :].copy()
            foreground = foreground[::-1, :].copy()

        if self.rng.random() < 0.45:
            gain = self.rng.uniform(0.88, 1.12)
            bias = self.rng.uniform(-0.05, 0.05)
            inputs[0] = np.clip(inputs[0] * gain + bias, 0.0, 1.0)
        return inputs, target, foreground

    def __getitem__(self, index: int) -> dict[str, torch.Tensor]:
        row = self.rows[index]
        input_gray = read_gray(self.dataset_dir / row["input"])
        target = read_gray(self.dataset_dir / row["defect_mask"])
        foreground = read_gray(self.dataset_dir / row["foreground_mask"])
        height, width = input_gray.shape
        crop = self._make_crop(height, width, target, foreground)

        input_crop = input_gray[crop.top: crop.top + crop.size, crop.left: crop.left + crop.size]
        target_crop = target[crop.top: crop.top + crop.size, crop.left: crop.left + crop.size]
        foreground_crop = foreground[crop.top: crop.top + crop.size, crop.left: crop.left + crop.size]

        inputs = build_input_channels(input_crop)
        target_f = (target_crop.astype(np.float32) / 255.0)[None, :, :]
        foreground_f = (foreground_crop.astype(np.float32) / 255.0)[None, :, :]
        inputs, target_f[0], foreground_f[0] = self._augment(inputs, target_f[0], foreground_f[0])

        return {
            "input": torch.from_numpy(inputs),
            "target": torch.from_numpy(target_f),
            "foreground": torch.from_numpy(foreground_f),
        }


class ConvBlock(nn.Module):
    def __init__(self, in_channels: int, out_channels: int) -> None:
        super().__init__()
        self.net = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.SiLU(inplace=True),
            nn.Conv2d(out_channels, out_channels, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.SiLU(inplace=True),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


class TinyUNet(nn.Module):
    def __init__(self, in_channels: int = 3, base_channels: int = 16) -> None:
        super().__init__()
        self.input_channels = in_channels
        c = base_channels
        self.enc1 = ConvBlock(in_channels, c)
        self.enc2 = ConvBlock(c, c * 2)
        self.enc3 = ConvBlock(c * 2, c * 4)
        self.bridge = ConvBlock(c * 4, c * 8)
        self.dec3 = ConvBlock(c * 8 + c * 4, c * 4)
        self.dec2 = ConvBlock(c * 4 + c * 2, c * 2)
        self.dec1 = ConvBlock(c * 2 + c, c)
        self.head = nn.Conv2d(c, 1, 1)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        e1 = self.enc1(x)
        e2 = self.enc2(F.max_pool2d(e1, 2))
        e3 = self.enc3(F.max_pool2d(e2, 2))
        b = self.bridge(F.max_pool2d(e3, 2))

        d3 = F.interpolate(b, size=e3.shape[-2:], mode="bilinear", align_corners=False)
        d3 = self.dec3(torch.cat([d3, e3], dim=1))
        d2 = F.interpolate(d3, size=e2.shape[-2:], mode="bilinear", align_corners=False)
        d2 = self.dec2(torch.cat([d2, e2], dim=1))
        d1 = F.interpolate(d2, size=e1.shape[-2:], mode="bilinear", align_corners=False)
        d1 = self.dec1(torch.cat([d1, e1], dim=1))
        return self.head(d1)


def dice_loss(logits: torch.Tensor, target: torch.Tensor, eps: float = 1e-6) -> torch.Tensor:
    prob = torch.sigmoid(logits)
    intersection = torch.sum(prob * target, dim=(1, 2, 3))
    denominator = torch.sum(prob + target, dim=(1, 2, 3))
    return 1.0 - torch.mean((2.0 * intersection + eps) / (denominator + eps))


def segmentation_loss(logits: torch.Tensor, target: torch.Tensor, foreground: torch.Tensor) -> torch.Tensor:
    # Creases can cross text, so positive crease pixels stay learnable. But
    # foreground pixels without a crease are hard negatives: text, ruled lines,
    # QR blocks, and diagrams must not become removable paper defects.
    background_weight = torch.where(target < 0.5, 1.55, 1.0)
    foreground_weight = torch.where((foreground > 0.2) & (target < 0.5), 5.0, background_weight)
    bce = F.binary_cross_entropy_with_logits(
        logits,
        target,
        weight=foreground_weight,
        pos_weight=torch.tensor(1.05, device=logits.device),
    )
    return bce + dice_loss(logits, target) * 0.32


def split_rows(rows: list[dict], val_ratio: float, seed: int) -> tuple[list[dict], list[dict]]:
    shuffled = rows.copy()
    random.Random(seed).shuffle(shuffled)
    val_count = max(1, int(round(len(shuffled) * val_ratio)))
    return shuffled[val_count:], shuffled[:val_count]


def run_epoch(
    model: nn.Module,
    loader: DataLoader,
    device: torch.device,
    optimizer: torch.optim.Optimizer | None,
) -> float:
    train = optimizer is not None
    model.train(train)
    total_loss = 0.0
    total_count = 0
    for batch in loader:
        inputs = batch["input"].to(device)
        target = batch["target"].to(device)
        foreground = batch["foreground"].to(device)
        with torch.set_grad_enabled(train):
            logits = model(inputs)
            loss = segmentation_loss(logits, target, foreground)
            if train:
                optimizer.zero_grad(set_to_none=True)
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 2.0)
                optimizer.step()
        total_loss += float(loss.detach().cpu()) * inputs.shape[0]
        total_count += inputs.shape[0]
    return total_loss / max(1, total_count)


def predict_full_image(model: nn.Module, image_bgr: np.ndarray, device: torch.device, tile_size: int = 384, overlap: int = 96) -> np.ndarray:
    gray = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)
    height, width = gray.shape
    stride = tile_size - overlap
    ys = list(range(0, max(1, height - tile_size + 1), stride))
    xs = list(range(0, max(1, width - tile_size + 1), stride))
    if ys[-1] != max(0, height - tile_size):
        ys.append(max(0, height - tile_size))
    if xs[-1] != max(0, width - tile_size):
        xs.append(max(0, width - tile_size))

    pad_h = max(height, tile_size)
    pad_w = max(width, tile_size)
    padded = cv2.copyMakeBorder(gray, 0, pad_h - height, 0, pad_w - width, cv2.BORDER_REFLECT_101)
    acc = np.zeros((pad_h, pad_w), dtype=np.float32)
    weight = np.zeros((pad_h, pad_w), dtype=np.float32)
    window = np.outer(np.hanning(tile_size), np.hanning(tile_size)).astype(np.float32)
    window = np.maximum(window, 0.08)

    model.eval()
    expected_channels = int(getattr(model, "input_channels", next(model.parameters()).shape[1]))
    with torch.no_grad():
        for y in ys:
            for x in xs:
                crop = padded[y: y + tile_size, x: x + tile_size]
                inputs = torch.from_numpy(build_input_channels(crop, expected_channels)[None, :, :, :]).to(device)
                prob = torch.sigmoid(model(inputs))[0, 0].detach().cpu().numpy()
                acc[y: y + tile_size, x: x + tile_size] += prob * window
                weight[y: y + tile_size, x: x + tile_size] += window
    return np.clip(acc[:height, :width] / np.maximum(weight[:height, :width], 1e-6), 0.0, 1.0)


def fit_cell(image: np.ndarray, label: str, width: int = 280, height: int = 360) -> np.ndarray:
    if image.ndim == 2:
        image = cv2.cvtColor(image, cv2.COLOR_GRAY2BGR)
    source_h, source_w = image.shape[:2]
    scale = min(width / source_w, (height - 30) / source_h)
    resized_w = max(1, int(round(source_w * scale)))
    resized_h = max(1, int(round(source_h * scale)))
    resized = cv2.resize(image, (resized_w, resized_h), interpolation=cv2.INTER_AREA)
    canvas = np.full((height, width, 3), 255, dtype=np.uint8)
    x = (width - resized_w) // 2
    y = 28 + (height - 30 - resized_h) // 2
    canvas[y: y + resized_h, x: x + resized_w] = resized
    cv2.putText(canvas, label, (8, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.52, (0, 0, 170), 1, cv2.LINE_AA)
    return canvas


def write_validation_sheet(
    model: nn.Module,
    dataset_dir: Path,
    rows: list[dict],
    out_path: Path,
    device: torch.device,
) -> None:
    sheet_rows = []
    for row in rows[:8]:
        image = read_bgr(dataset_dir / row["input"])
        target = read_gray(dataset_dir / row["defect_mask"])
        prob = predict_full_image(model, image, device)
        pred = (prob * 255.0).astype(np.uint8)
        overlay = image.copy()
        red = np.zeros_like(image)
        red[:, :, 2] = 255
        overlay = np.where((prob[:, :, None] > 0.58), cv2.addWeighted(overlay, 0.55, red, 0.45, 0.0), overlay)
        sheet_rows.append(
            np.concatenate(
                [
                    fit_cell(image, f"{row['id']} input"),
                    fit_cell(target, "target"),
                    fit_cell(pred, "prediction"),
                    fit_cell(overlay, "overlay"),
                ],
                axis=1,
            ),
        )
    if sheet_rows:
        write_image(out_path, np.concatenate(sheet_rows, axis=0))


def main() -> None:
    args = parse_args()
    set_seeds(args.seed)
    repo_root = Path(__file__).resolve().parent.parent
    dataset_dir = (repo_root / args.dataset).resolve()
    out_dir = (repo_root / args.out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    rows = load_manifest(dataset_dir)
    train_rows, val_rows = split_rows(rows, args.val_ratio, args.seed)
    device = select_device()
    print(f"Device: {device}")
    print(f"Rows: train={len(train_rows)} val={len(val_rows)}")

    train_set = CreaseDataset(dataset_dir, train_rows, args.crop_size, train=True, seed=args.seed)
    val_set = CreaseDataset(dataset_dir, val_rows, args.crop_size, train=False, seed=args.seed + 1)
    train_loader = DataLoader(train_set, batch_size=args.batch_size, shuffle=True, num_workers=args.num_workers)
    val_loader = DataLoader(val_set, batch_size=args.batch_size, shuffle=False, num_workers=args.num_workers)

    model = TinyUNet(in_channels=5, base_channels=args.base_channels).to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.learning_rate, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=max(1, args.epochs))

    history = []
    best_val = math.inf
    best_state = None
    for epoch in range(1, args.epochs + 1):
        train_loss = run_epoch(model, train_loader, device, optimizer)
        with torch.no_grad():
            val_loss = run_epoch(model, val_loader, device, optimizer=None)
        scheduler.step()
        history.append({"epoch": epoch, "train_loss": train_loss, "val_loss": val_loss})
        print(f"epoch {epoch:03d}: train={train_loss:.4f} val={val_loss:.4f}")
        if val_loss < best_val:
            best_val = val_loss
            best_state = {key: value.detach().cpu() for key, value in model.state_dict().items()}

    if best_state is not None:
        model.load_state_dict(best_state)

    checkpoint = {
        "model": model.state_dict(),
        "model_name": "TinyUNetCreaseMask",
        "input_channels": [
            "luminance",
            "local_dark_delta",
            "local_bright_delta",
            "broad_dark_delta",
            "gradient_magnitude",
        ],
        "in_channels": 5,
        "base_channels": args.base_channels,
        "crop_size": args.crop_size,
        "dataset": str(dataset_dir),
        "history": history,
    }
    torch.save(checkpoint, out_dir / "model.pt")
    (out_dir / "metrics.json").write_text(json.dumps(history, indent=2) + "\n", encoding="utf-8")
    write_validation_sheet(model, dataset_dir, val_rows, out_dir / "validation-contact-sheet.jpg", device)
    print(f"Wrote checkpoint: {out_dir / 'model.pt'}")
    print(f"Wrote validation sheet: {out_dir / 'validation-contact-sheet.jpg'}")


if __name__ == "__main__":
    main()
